site_name: TextMiner Pro
site_description: 파이썬 기반 고급 텍스트 분석 도구
site_author: InjinSung
repo_url: https://github.com/jagari/textminer-pro
site_url: https://jagari.github.io/textminer-pro/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - navigation.top
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - 홈: index.md
  - 시작하기: 
    - 설치 방법: installation.md
    - 퀵 스타트: quickstart.md
  - 기능:
    - 불용어 제거: features/stopwords.md
    - 키워드 추출: features/keywords.md
    - 텍스트 요약: features/summarization.md
    - 언어 감지: features/language_detection.md
  - API 레퍼런스: api_reference.md
  - 기여하기: contributing.md

plugins:
  - search:
      lang: ko
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 2
